networks:
  fabric-network:
    driver: bridge
    name: fabric-network

services:
  initializer_woodsupply:
    networks:
      - fabric-network
    build:
      context: ./Wood_Supply
      dockerfile: Dockerfile
    image: yfw-woodsupply-ca:latest
    container_name: container-initializer-woodsupply-ca
    hostname: woodsupply
    ports:
      - "8054:8054"
    volumes:
      - ./Wood_Supply/crypto/:/etc/hyperledger/
      - ./_scripts/:/etc/scripts/
    environment:
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/server/tls-ca
      - FABRIC_CA_SERVER_TLS_CLIENTAUTH_TYPE=NoClientCert
    command: >
      bash -c "
      echo 'Starting Fabric TLS CA server...';
      fabric-ca-server start -b tlsadmin:tlsadminpw & 
      sleep 3;
      echo 'Running enroll-tls.sh...';
      ./enroll-tls-new.sh;
      echo 'Initializer completed.'"
    restart: "no" # Ensure this container exits after completing its task

  woodsupply-ca:
    networks:
      - fabric-network
    build:
      context: ./Wood_Supply
      dockerfile: Dockerfile
    image: fabric/woodsupply-ca:latest
    container_name: woodsupply-ca
    hostname: woodsupply
    ports:
      - "8054:8054"
    volumes:
      - ./Wood_Supply/crypto/:/etc/hyperledger/
      - ./_scripts/:/etc/scripts/
      - ./_shared_certs/:/etc/_shared_certs/
      - ./Wood_Supply/_env/:/etc/_env/
    depends_on:
      initializer_woodsupply:
        condition: service_completed_successfully
    environment:
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/server/ca
      - FABRIC_CA_SERVER_TLS_CLIENTAUTH_TYPE=RequireAndVerifyClientCert
    command: >
      bash -c "
      echo 'Starting Fabric ORG CA server...';
      fabric-ca-server start -b admin:adminpw &
      sleep 3;
      echo 'Running enroll-ca.sh...';
      ./enroll-ca-new.sh;
      wait;
      if [ -f /etc/_env/env ]; then
        source /etc/_env/env && fabric-ca-server start;
      else
        echo 'Env file not found!';
        exit 1;
      fi"