services:
  initializer:
    build:
      context: ./Furnitures_Makers
      dockerfile: Dockerfile
    image: fabric/furnituresmakers-ca:latest
    container_name: container-initializer-ca
    hostname: tlsadmin
    ports:
      - "7054:7054"
    volumes:
      - ./Furnitures_Makers/crypto/:/etc/hyperledger/
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/server/tls-ca
      - FABRIC_CA_SERVER_TLS_CLIENTAUTH_TYPE=NoClientCert
    command: >
      bash -c "
      echo 'Starting Fabric CA server...';
      fabric-ca-server start -b tlsadmin:tlsadminpw & 
      sleep 5;
      echo 'Running enroll-tls.sh...';
      ./enroll-tls.sh;
      echo 'Initializer completed.';
      wait"
    restart: "no" # Ensure this container exits after completing its task