FROM hyperledger/fabric-ca:latest

WORKDIR /etc/hyperledger

#RUN mkdir -p server client

#COPY fabric-ca-server-config.yaml /etc/hyperledger/server/


EXPOSE 7056

#CMD ["sh", "-c", "fabric-ca-server start -b admin:adminpw -d"]
