FROM hyperledger/fabric-ca:latest

WORKDIR /etc/scripts

#RUN mkdir -p server client

#COPY fabric-ca-server-config.yaml /etc/hyperledger/server/

EXPOSE 7054

#CMD ["sh", "-c", "fabric-ca-server start -b admin:adminpw -d"]
